remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Electronic Objects Blog 
description: My blog for 4929C during spring semester 2023. 
show_downloads: false
